name: test

on: [push]

permissions: read-all

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: code
        uses: actions/checkout@v4

      - name: go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23

      - name: test
        run: |
          go get -v -t -d ./...
          go test -short -cover -coverprofile=coverage.out -covermode=atomic ./...

      - name: codecov.io coverage
        uses: codecov/codecov-action@v4.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
